import { Business } from '@/types/business';

export const mockNexoBusiness: Business = {
  id: 'biz-nexo-001',
  slug: 'nexosoluciones',
  name: 'Nexo Soluciones',
  isVerified: true,
  category: 'Soluciones Tecnológicas & Consultoría B2B',
  bio: 'Impulsamos el crecimiento de empresas mediante infraestructura en la nube, digitalización de procesos y hardware NFC para networking corporativo.',
  bannerUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200&auto=format&fit=crop',
  logoUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=400&auto=format&fit=crop',
  themeColor: '#0284c7', // Cyan / Sky blue
  phone: '+52 55 8421 9000',
  whatsapp: '+525584219000',
  email: 'contacto@nexosoluciones.mx',
  address: 'Av. Paseo de la Reforma 222, Piso 18, Juárez, Cuauhtémoc, CDMX',
  googleMapsUrl: 'https://maps.google.com/?q=Paseo+de+la+Reforma+222+CDMX',
  catalogUrl: 'https://nexosoluciones.mx/catalogo-corporativo-2026.pdf',
  catalogTitle: 'Catálogo de Servicios 2026',
  websiteUrl: 'https://nexosoluciones.mx',
  cards: [
    {
      id: 'card-01',
      cardCode: 'NX-8821',
      businessId: 'biz-nexo-001',
      status: 'ACTIVE',
      totalTaps: 342,
      lastTapAt: '2026-09-28T14:20:00Z',
      createdAt: '2026-01-15T09:00:00Z',
    },
    {
      id: 'card-02',
      cardCode: 'NX-9940',
      businessId: 'biz-nexo-001',
      status: 'ACTIVE',
      totalTaps: 128,
      lastTapAt: '2026-09-28T11:05:00Z',
      createdAt: '2026-02-10T12:00:00Z',
    },
  ],
  links: [
    {
      id: 'link-wa',
      businessId: 'biz-nexo-001',
      type: 'whatsapp',
      title: 'WhatsApp',
      subtitle: 'Chatea con nosotros en tiempo real',
      url: 'https://wa.me/525584219000?text=Hola%20Nexo%20Soluciones,%20me%20gustar%C3%ADa%20solicitar%20informaci%C3%B3n.',
      iconName: 'whatsapp',
      order: 1,
      isActive: true,
      highlighted: true,
    },
    {
      id: 'link-call',
      businessId: 'biz-nexo-001',
      type: 'phone',
      title: 'Llamar ahora',
      subtitle: '+52 55 8421 9000',
      url: 'tel:+525584219000',
      iconName: 'phone',
      order: 2,
      isActive: true,
    },
    {
      id: 'link-ig',
      businessId: 'biz-nexo-001',
      type: 'instagram',
      title: 'Síguenos en Instagram',
      subtitle: '@nexosoluciones.mx',
      url: 'https://instagram.com/nexosoluciones',
      iconName: 'instagram',
      order: 3,
      isActive: true,
    },
    {
      id: 'link-fb',
      businessId: 'biz-nexo-001',
      type: 'facebook',
      title: 'Visítanos en Facebook',
      subtitle: '/nexosolucionesoficial',
      url: 'https://facebook.com/nexosoluciones',
      iconName: 'facebook',
      order: 4,
      isActive: true,
    },
    {
      id: 'link-li',
      businessId: 'biz-nexo-001',
      type: 'linkedin',
      title: 'Conéctate en LinkedIn',
      subtitle: 'Nexo Soluciones Corporativas',
      url: 'https://linkedin.com/company/nexo-soluciones',
      iconName: 'linkedin',
      order: 5,
      isActive: true,
    },
    {
      id: 'link-web',
      businessId: 'biz-nexo-001',
      type: 'website',
      title: 'Conoce nuestro sitio web',
      subtitle: 'nexosoluciones.mx',
      url: 'https://nexosoluciones.mx',
      iconName: 'globe',
      order: 6,
      isActive: true,
    },
  ],
  customization: {
    backgroundMode: 'full',
    backgroundOverlay: 'dark',
    buttonShape: 'rounded',
    iconColorMode: 'official',
    fontFamily: 'Inter',
  },
  plan: 'ENTERPRISE',
  accountStatus: 'ACTIVE',
  createdAt: '2026-01-10T08:00:00Z',
};

export const mockRestaurantBusiness: Business = {
  id: 'biz-fuego-002',
  slug: 'fuego-lena-grill',
  name: 'Fuego & Leña Steakhouse',
  isVerified: true,
  category: 'Restaurante & Cortes Finos a la Parrilla',
  bio: 'La mejor experiencia gastronómica de cortes premium y cocina de autor al fuego de leña. Ambiente exclusivo y coctelería artesanal.',
  bannerUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=1200&auto=format&fit=crop',
  logoUrl: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?q=80&w=400&auto=format&fit=crop',
  themeColor: '#f59e0b', // Amber / Orange
  phone: '+52 55 9876 5432',
  whatsapp: '+525598765432',
  email: 'reservaciones@fuegoylena.com',
  address: 'Calle Durango 185, Col. Roma Norte, Cuauhtémoc, CDMX',
  googleMapsUrl: 'https://maps.google.com/?q=Roma+Norte+CDMX',
  catalogUrl: 'https://fuegoylena.com/menu-digital.pdf',
  catalogTitle: 'Carta de Vinos y Platillos',
  websiteUrl: 'https://fuegoylena.com',
  plan: 'PRO',
  accountStatus: 'ACTIVE',
  createdAt: '2026-02-01T10:00:00Z',
  quickAccess: {
    enabled: true,
    showPhone: true,
    showEmail: false,
    showMaps: true,
    showCatalog: true,
  },
  cards: [
    {
      id: 'card-fl-01',
      cardCode: 'FL-01',
      businessId: 'biz-fuego-002',
      status: 'ACTIVE',
      totalTaps: 512,
      lastTapAt: '2026-09-28T18:30:00Z',
      createdAt: '2026-02-01T10:00:00Z',
    },
    {
      id: 'card-fl-02',
      cardCode: 'FL-02',
      businessId: 'biz-fuego-002',
      status: 'ACTIVE',
      totalTaps: 180,
      lastTapAt: '2026-09-28T15:10:00Z',
      createdAt: '2026-02-01T10:00:00Z',
    },
  ],
  links: [
    {
      id: 'fl-link-menu',
      businessId: 'biz-fuego-002',
      type: 'menu',
      title: 'Ver Menú y Especiales del Chef',
      subtitle: 'Cortes importados, pastas y mariscos',
      url: 'https://fuegoylena.com/menu',
      iconName: 'utensils',
      customColor: 'amber',
      order: 1,
      isActive: true,
      highlighted: true,
    },
    {
      id: 'fl-link-book',
      businessId: 'biz-fuego-002',
      type: 'booking',
      title: 'Reservar Mesa en Línea',
      subtitle: 'Elige horario y número de comensales',
      url: 'https://fuegoylena.com/reservar',
      iconName: 'calendar',
      customColor: 'purple',
      order: 2,
      isActive: true,
    },
    {
      id: 'fl-link-wa',
      businessId: 'biz-fuego-002',
      type: 'whatsapp',
      title: 'WhatsApp para Pedidos & Eventos',
      subtitle: '+52 55 9876 5432',
      url: 'https://wa.me/525598765432',
      iconName: 'whatsapp',
      order: 3,
      isActive: true,
    },
    {
      id: 'fl-link-ig',
      businessId: 'biz-fuego-002',
      type: 'instagram',
      title: 'Instagram @fuegoylenagrill',
      subtitle: 'Conoce nuestras fotos y platillos del día',
      url: 'https://instagram.com/fuegoylenagrill',
      iconName: 'instagram',
      order: 4,
      isActive: true,
    },
  ],
  customization: {
    backgroundMode: 'full',
    backgroundOverlay: 'dark',
    buttonShape: 'pill',
    iconColorMode: 'official',
    fontFamily: 'Playfair Display',
  },
};

export const mockSalonBusiness: Business = {
  id: 'biz-aura-003',
  slug: 'aura-beauty-spa',
  name: 'Aura Glow Nails & Spa',
  isVerified: true,
  category: 'Estética, Uñas Esculpidas & Spa Facial',
  bio: 'Estudio de belleza especializado en manicura rusa, nail art de tendencia, lash lifting y tratamientos faciales personalizados.',
  bannerUrl: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?q=80&w=1200&auto=format&fit=crop',
  logoUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=400&auto=format&fit=crop',
  themeColor: '#ec4899', // Pink
  phone: '+52 55 4321 8765',
  whatsapp: '+525543218765',
  email: 'citas@auraglowspa.mx',
  address: 'Av. Horacio 540, Polanco, Miguel Hidalgo, CDMX',
  googleMapsUrl: 'https://maps.google.com/?q=Polanco+CDMX',
  catalogUrl: 'https://auraglowspa.mx/catalogo-disenos.pdf',
  catalogTitle: 'Catálogo de Diseños & Precios',
  websiteUrl: 'https://auraglowspa.mx',
  plan: 'PRO',
  accountStatus: 'ACTIVE',
  createdAt: '2026-03-05T11:00:00Z',
  quickAccess: {
    enabled: true,
    showPhone: false,
    showEmail: false,
    showMaps: true,
    showCatalog: true,
  },
  cards: [
    {
      id: 'card-aura-77',
      cardCode: 'AURA-77',
      businessId: 'biz-aura-003',
      status: 'ACTIVE',
      totalTaps: 320,
      lastTapAt: '2026-09-28T16:45:00Z',
      createdAt: '2026-03-05T11:00:00Z',
    },
  ],
  links: [
    {
      id: 'aura-link-book',
      businessId: 'biz-aura-003',
      type: 'booking',
      title: 'Agendar Cita en Línea',
      subtitle: 'Reserva tu horario con tu manicurista favorita',
      url: 'https://auraglowspa.mx/agendar',
      iconName: 'calendar',
      customColor: 'pink',
      order: 1,
      isActive: true,
      highlighted: true,
    },
    {
      id: 'aura-link-wa',
      businessId: 'biz-aura-003',
      type: 'whatsapp',
      title: 'WhatsApp Directo para Consultas',
      subtitle: 'Respuestas inmediatas de 9:00 a 20:00',
      url: 'https://wa.me/525543218765',
      iconName: 'whatsapp',
      order: 2,
      isActive: true,
    },
    {
      id: 'aura-link-ig',
      businessId: 'biz-aura-003',
      type: 'instagram',
      title: 'Galería de Diseños en Instagram',
      subtitle: '@auraglow.nails',
      url: 'https://instagram.com/auraglow.nails',
      iconName: 'instagram',
      order: 3,
      isActive: true,
    },
    {
      id: 'aura-link-custom',
      businessId: 'biz-aura-003',
      type: 'custom',
      title: 'Promociones del Mes',
      subtitle: '2x1 en Nail Art los días jueves',
      url: 'https://auraglowspa.mx/promos',
      iconName: 'sparkles',
      customColor: 'purple',
      order: 4,
      isActive: true,
    },
  ],
  customization: {
    backgroundMode: 'full',
    backgroundOverlay: 'light',
    buttonShape: 'tile',
    iconColorMode: 'monochrome',
    iconCustomColor: '#db2777',
    fontFamily: 'Great Vibes',
  },
};

// Map of businesses by slug for mock backend
export const mockBusinessesDatabase: Record<string, Business> = {
  nexosoluciones: mockNexoBusiness,
  'fuego-lena-grill': mockRestaurantBusiness,
  'aura-beauty-spa': mockSalonBusiness,
};

// NFC card router lookup database
export const mockCardsDatabase: Record<string, string> = {
  'NX-8821': 'nexosoluciones',
  'NX-9940': 'nexosoluciones',
  'FL-01': 'fuego-lena-grill',
  'FL-02': 'fuego-lena-grill',
  'AURA-77': 'aura-beauty-spa',
};

